In [1]:
#INSTALAR LIBRERIAS
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install openpyxl

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.1.3)
Requirement already satisfied: matplotlib in /opt/anaconda3/lib/python3.13/site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /opt/anaconda3/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /opt/anaconda3/lib/python3.13/site-packages (from seaborn) (2.1.3)
Requirement already satisfied: pandas>=1.2 in /opt/anaconda3/lib/python3.13/site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/anaconda3/lib/python3.13/site-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: openpyxl in /opt/anaconda3/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et_xmlfile in /opt/anaconda3/lib/python3.13/site-packages (from openpyxl) (1.1.0)

In [15]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
#Convertimos el dataset en dataframe
df= pd.read_csv("listings.csv") # CAMBIAR EL NOMBRE 
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2708,https://www.airbnb.com/rooms/2708,20250617032927,2025-06-17,city scrape,"Run Runyon, Beaut Furn Mirror Mini-Suit w/ Fir...",Run Runyon Canyon<br /><br />Gym & Sauna <br /...,"Walk and run to Runyon Canyon, it is open!<br ...",https://a0.muscache.com/pictures/hosting/Hosti...,3008,...,4.98,4.95,4.86,NaN,t,2,0,2,0,0.33
1,2732,https://www.airbnb.com/rooms/2732,20250617032927,2025-06-17,city scrape,Zen Life at the Beach,An oasis of tranquility awaits you.,"This is the best part of Santa Monica. Quiet, ...",https://a0.muscache.com/pictures/1082993/c5a99...,3041,...,4.48,4.91,4.22,228269,f,2,1,1,0,0.14
2,2864,https://www.airbnb.com/rooms/2864,20250617032927,2025-06-17,previous scrape,* Beautiful Master Suite/Jacuzzi Tub/*,Centrally located.... Furnished with King Size...,What makes the neighborhood unique is that the...,https://a0.muscache.com/pictures/23817858/de20...,3207,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
3,6033,https://www.airbnb.com/rooms/6033,20250617032927,2025-06-17,previous scrape,Poolside Serenity Studio,Our distinctive bachelor's studio for 1-3 gues...,NaN,https://a0.muscache.com/pictures/458111/986c76...,11619,...,4.35,4.65,4.29,NaN,f,6,3,3,0,0.10
4,6931,https://www.airbnb.com/rooms/6931,20250617032927,2025-06-17,city scrape,"RUN Runyon, Beau Furn Rms Terrace Hollyw Hill ...",Run Runyon Canyon & Views<br /><br />Gym & Sau...,We are in the middle of one of the great citie...,https://a0.muscache.com/pictures/miso/Hosting-...,3008,...,4.91,4.71,4.76,NaN,t,2,0,2,0,0.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45416,1443394805958459680,https://www.airbnb.com/rooms/1443394805958459680,20250617032927,2025-06-17,city scrape,"Motel 6 Claremont, Ca_1 King Bed | Nsmk","Motel 6 Claremont, Ca_1 King Bed | Nsmk",NaN,https://a0.muscache.com/pictures/prohost-api/H...,674118442,...,NaN,NaN,NaN,NaN,t,79,79,0,0,NaN
45417,1443394831515560629,https://www.airbnb.com/rooms/1443394831515560629,20250617032927,2025-06-17,city scrape,"Motel 6 Claremont, Ca_2 Queen Beds | Smo","Motel 6 Claremont, Ca_2 Queen Beds | Smo",NaN,https://a0.muscache.com/pictures/prohost-api/H...,674118442,...,NaN,NaN,NaN,NaN,t,79,79,0,0,NaN
45418,1443394885201303898,https://www.airbnb.com/rooms/1443394885201303898,20250617032927,2025-06-17,city scrape,"Motel 6 Claremont, Ca_2 Queen Beds | Nsm","Motel 6 Claremont, Ca_2 Queen Beds | Nsm",NaN,https://a0.muscache.com/pictures/prohost-api/H...,674118442,...,NaN,NaN,NaN,NaN,t,79,79,0,0,NaN
45419,1443449500529637549,https://www.airbnb.com/rooms/1443449500529637549,20250617032927,2025-06-17,city scrape,Point Dume Summer Rental,Relax with the whole family at this peaceful p...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,115170752,...,NaN,NaN,NaN,STR22-0034,t,2,2,0,0,NaN
45420,1443465434447227262,https://www.airbnb.com/rooms/1443465434447227262,20250617032927,2025-06-17,city scrape,"SoCal Getaway Minutes from Disneyland, DTLA &C...",Stay at this centrally located getaway on the ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,30071757,...,NaN,NaN,NaN,NaN,t,2,1,0,1,NaN

In [17]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45421 entries, 0 to 45420
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            45421 non-null  int64
 1   listing_url                                   45421 non-null  object
 2   scrape_id                                     45421 non-null  int64
 3   last_scraped                                  45421 non-null  object
 4   source                                        45421 non-null  object
 5   name                                          45420 non-null  object
 6   description                                   44399 non-null  object
 7   neighborhood_overview                         20350 non-null  object
 8   picture_url                                   45421 non-null  object
 9   host_id                                       45421 non-null  int64
 10  host_url                                      45421 non-null  object
 11  host_name                                     45416 non-null  object
 12  host_since                                    45414 non-null  object
 13  host_location                                 34640 non-null  object
 14  host_about                                    24875 non-null  object
 15  host_response_time                            35028 non-null  object
 16  host_response_rate                            35028 non-null  object
 17  host_acceptance_rate                          35640 non-null  object
 18  host_is_superhost                             43852 non-null  object
 19  host_thumbnail_url                            45414 non-null  object
 20  host_picture_url                              45414 non-null  object
 21  host_neighbourhood                            35914 non-null  object
 22  host_listings_count                           45414 non-null  float64
 23  host_total_listings_count                     45414 non-null  float64
 24  host_verifications                            45414 non-null  object
 25  host_has_profile_pic                          45414 non-null  object
 26  host_identity_verified                        45414 non-null  object
 27  neighbourhood                                 20351 non-null  object
 28  neighbourhood_cleansed                        45421 non-null  object
 29  neighbourhood_group_cleansed                  45421 non-null  object
 30  latitude                                      45421 non-null  float64
 31  longitude                                     45421 non-null  float64
 32  property_type                                 45421 non-null  object
 33  room_type                                     45421 non-null  object
 34  accommodates                                  45421 non-null  int64
 35  bathrooms                                     36588 non-null  float64
 36  bathrooms_text                                45367 non-null  object
 37  bedrooms                                      42358 non-null  float64
 38  beds                                          36545 non-null  float64
 39  amenities                                     45421 non-null  object
 40  price                                         36405 non-null  object
 41  minimum_nights                                45421 non-null  int64
 42  maximum_nights                                45421 non-null  int64
 43  minimum_minimum_nights                        45421 non-null  int64
 44  maximum_minimum_nights                        45421 non-null  int64
 45  minimum_maximum_nights                        45421 non-null  int64
 46  maximum_maximum_nights                        45421 non-null  int64
 47  minimum_nights_avg_ntm                        45421 non-null  float64
 48  maximum_nights_avg_ntm                        45421 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              41916 non-null  object
 51  availability_30                               45421 non-null  int64
 52  availability_60                               45421 non-null  int64
 53  availability_90                               45421 non-null  int64
 54  availability_365                              45421 non-null  int64
 55  calendar_last_scraped                         45421 non-null  object
 56  number_of_reviews                             45421 non-null  int64
 57  number_of_reviews_ltm                         45421 non-null  int64
 58  number_of_reviews_l30d                        45421 non-null  int64
 59  availability_eoy                              45421 non-null  int64
 60  number_of_reviews_ly                          45421 non-null  int64
 61  estimated_occupancy_l365d                     45421 non-null  int64
 62  estimated_revenue_l365d                       36405 non-null  float64
 63  first_review                                  32849 non-null  object
 64  last_review                                   32849 non-null  object
 65  review_scores_rating                          32849 non-null  float64
 66  review_scores_accuracy                        32841 non-null  float64
 67  review_scores_cleanliness                     32841 non-null  float64
 68  review_scores_checkin                         32833 non-null  float64
 69  review_scores_communication                   32839 non-null  float64
 70  review_scores_location                        32832 non-null  float64
 71  review_scores_value                           32831 non-null  float64
 72  license                                       12882 non-null  object
 73  instant_bookable                              45421 non-null  object
 74  calculated_host_listings_count                45421 non-null  int64
 75  calculated_host_listings_count_entire_homes   45421 non-null  int64
 76  calculated_host_listings_count_private_rooms  45421 non-null  int64
 77  calculated_host_listings_count_shared_rooms   45421 non-null  int64
 78  reviews_per_month                             32849 non-null  float64
dtypes: float64(19), int64(24), object(36)
memory usage: 27.4+ MB

***Un array 2D con las columnas***

In [ ]:
columnas1 = df[['host_name', 'host_since','host_neighbourhood', 'property_type', 'room_type','price']] #pueden ser consecutivas o no consecutivas
columnas1

,host_name,host_since,host_neighbourhood,property_type,room_type,price
0,Chas.,2008-09-16,Hollywood,Private room in rental unit,Private room,$110.00
1,Louise-Diane,2008-09-17,Santa Monica,Private room in rental unit,Private room,$118.00
2,Bernadine,2008-09-25,Bellflower,Entire rental unit,Entire home/apt,NaN
3,Sarah,2009-03-28,Woodland Hills/Warner Center,Entire bungalow,Entire home/apt,NaN
4,Chas.,2008-09-16,Hollywood,Private room in rental unit,Private room,$114.00
...,...,...,...,...,...,...
45416,Jan,2025-01-20,Webster Park North,Entire villa,Entire home/apt,$100.00
45417,Jan,2025-01-20,Webster Park North,Entire villa,Entire home/apt,$100.00
45418,Jan,2025-01-20,Webster Park North,Entire villa,Entire home/apt,$100.00
45419,Rachel,2017-02-06,Central Malibu,Entire home,Entire home/apt,$479.00
45420,Theresa,2015-03-26,Hawaiian Gardens,Entire condo,Entire home/apt,$169.00

In [21]:
#Convertir array a CSV
columnas1.to_csv("Entregable(a).csv")

*** (b) Un array 2D con las filas. ***

In [22]:
df2= df.iloc[ [1] + [50] + list(range(100, 201)) + [499] + [500] + [605] + [1500] + [8000] + [15000] , : ] 
df2

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
1,2732,https://www.airbnb.com/rooms/2732,20250617032927,2025-06-17,city scrape,Zen Life at the Beach,An oasis of tranquility awaits you.,"This is the best part of Santa Monica. Quiet, ...",https://a0.muscache.com/pictures/1082993/c5a99...,3041,...,4.48,4.91,4.22,228269,f,2,1,1,0,0.14
50,131557,https://www.airbnb.com/rooms/131557,20250617032927,2025-06-18,city scrape,sweet little apt,"The heart of Echo Park, walking distance to bu...",NaN,https://a0.muscache.com/pictures/103231642/bd1...,78804,...,4.83,4.66,4.59,NaN,f,3,3,0,0,0.48
100,20585,https://www.airbnb.com/rooms/20585,20250617032927,2025-06-17,city scrape,"Private Studio, 6 Doors to Beach","One room guest unit, with kitchen*. Separate e...",This is a friendly neighborhood. Our street is...,https://a0.muscache.com/pictures/106212/f24db2...,77857,...,4.97,4.89,4.84,HSR24-001527,f,1,1,0,0,3.14
101,183319,https://www.airbnb.com/rooms/183319,20250617032927,2025-06-17,city scrape,Panoramic Ocean View Venice Beach,Craftsmen style penthouse with ocean view from...,About as close to the beach as you can live in...,https://a0.muscache.com/pictures/1170205/e2596...,867995,...,5.00,5.00,5.00,NaN,f,2,2,0,0,0.02
102,188081,https://www.airbnb.com/rooms/188081,20250617032927,2025-06-17,previous scrape,Griffith Park Home - Available Summer 2018,Amazing Private Street on the Oaks. Steps from...,NaN,https://a0.muscache.com/pictures/8725212/64d8c...,905689,...,NaN,NaN,NaN,NaN,f,2,1,1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,1257025,https://www.airbnb.com/rooms/1257025,20250617032927,2025-06-17,city scrape,Beach side heart of santa monica/P,Since the coronavirus we’re taking extra care ...,NaN,https://a0.muscache.com/pictures/20437296/a652...,6471245,...,4.77,4.95,4.68,217645,f,1,0,1,0,6.27
605,1042282,https://www.airbnb.com/rooms/1042282,20250617032927,2025-06-18,city scrape,Beautiful Family Garden House,Discounted for longer term stays<br />(availab...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,1180786,...,5.00,5.00,5.00,NaN,f,2,2,0,0,0.03
1500,4121396,https://www.airbnb.com/rooms/4121396,20250617032927,2025-06-17,previous scrape,Perfect 2BR pad!!! Steps from sand!,A spacious 2 bedroom (with parking included) t...,Everything that Classic Venice has to offer is...,https://a0.muscache.com/pictures/51809389/12a0...,17942313,...,4.67,4.88,4.38,NaN,f,1,1,0,0,0.19
8000,24806579,https://www.airbnb.com/rooms/24806579,20250617032927,2025-06-17,previous scrape,Reseda private bedroom and bathroom,This is a private bedroom with attached privat...,NaN,https://a0.muscache.com/pictures/cb51c333-a04b...,27772889,...,4.60,4.73,4.73,NaN,f,1,0,1,0,0.17
15000,47962676,https://www.airbnb.com/rooms/47962676,20250617032927,2025-06-18,city scrape,Hollywood Hills treehouse vibe with private yard,Private Hollywood Hills 2 bedroom home located...,"This is a nice neighborhood, walking distance ...",https://a0.muscache.com/pictures/af19b7f2-38b0...,4240522,...,5.00,4.95,4.94,HSR21-000103,f,1,1,0,0,5.11

In [23]:
#Convertir array a CSV
df2.to_csv("Entregable(b).csv")

***Un array 2D con las filas: 125, 252, 300-550, 700, 1000, 1250-la última fila y con las columnas: host_id, host_location, host_acceptance_rate, bathrooms, amenities, review_scores_value.***

In [24]:
df4= df.iloc[ [1] + [50] + list(range(100, 201)) + [499] + [500] + [605] + [1500] + [8000] + [15000] , [9]+ [13]+ [17]+ [35]+ [39] +[71] ] 
df4

,host_id,host_location,host_acceptance_rate,bathrooms,amenities,review_scores_value
1,3041,"Santa Monica, CA",50%,1.0,"[""Host greets you"", ""Free street parking"", ""Re...",4.22
50,78804,"Los Angeles, CA",43%,1.0,"[""Extra pillows and blankets"", ""Free street pa...",4.59
100,77857,"Los Angeles, CA",17%,1.0,"[""Stove"", ""Extra pillows and blankets"", ""Free ...",4.84
101,867995,"Los Angeles, CA",NaN,1.0,"[""Stove"", ""Extra pillows and blankets"", ""Free ...",5.00
102,905689,"Los Angeles, CA",NaN,NaN,"[""Heating"", ""Washer"", ""Dryer"", ""Free parking o...",NaN
...,...,...,...,...,...,...
500,6471245,"Santa Monica, CA",100%,1.0,"[""Stove"", ""Extra pillows and blankets"", ""Host ...",4.68
605,1180786,"Los Angeles, CA",90%,1.0,"[""Extra pillows and blankets"", ""Refrigerator"",...",5.00
1500,17942313,"Los Angeles, CA",NaN,NaN,"[""Heating"", ""Washer"", ""Shampoo"", ""Dryer"", ""Fir...",4.38
8000,27772889,"Los Angeles, CA",NaN,NaN,"[""Smoking allowed"", ""Essentials"", ""Free parkin...",4.73
15000,4240522,"Los Angeles, CA",98%,2.0,"[""Stove"", ""Extra pillows and blankets"", ""Coffe...",4.94

In [26]:
# Un array 2D con las filas: 125, 252, 300-550, 700, 1000, 1250-la última fila y con las columnas: host_id, host_location, host_acceptance_rate, bathrooms, amenities, review_scores_value
df5 = df.loc[[125, 252] + list(range(300, 551)) + [700, 1000, 1250, df.shape[0] - 1], ['host_id', 'host_location', 'host_acceptance_rate', 'bathrooms', 'amenities', 'review_scores_value']]
df5

,host_id,host_location,host_acceptance_rate,bathrooms,amenities,review_scores_value
125,76111,"Los Angeles, CA",NaN,3.0,"[""Stove"", ""Extra pillows and blankets"", ""Host ...",4.64
252,3393312,"Los Angeles, CA",100%,1.0,"[""Free street parking"", ""Refrigerator"", ""First...",4.91
300,2122283,"Los Angeles, CA",NaN,1.0,"[""BBQ grill"", ""Heating"", ""Washer"", ""Dryer"", ""A...",5.00
301,1678136,"São Paulo, Brazil",0%,4.0,"[""Heating"", ""Pets allowed"", ""Washer"", ""Shampoo...",4.43
302,309512,"Los Angeles, CA",95%,1.0,"[""Extra pillows and blankets"", ""Free street pa...",4.89
...,...,...,...,...,...,...
550,6483621,"Los Angeles, CA",80%,1.0,"[""Extra pillows and blankets"", ""Free street pa...",5.00
700,975343,"Monrovia, CA",67%,3.0,"[""Stove"", ""Coffee"", ""Free street parking"", ""Re...",4.73
1000,13789616,"Monterey Park, CA",100%,2.5,"[""Stove"", ""Extra pillows and blankets"", ""Free ...",4.66
1250,13735500,"Los Angeles, CA",NaN,NaN,"[""TV"", ""Washer"", ""Shampoo"", ""Carbon monoxide a...",4.79
45420,30071757,NaN,NaN,2.0,"[""Pets allowed"", ""Carbon monoxide alarm"", ""Was...",NaN

In [27]:
#Convertir array a CSV
df5.to_csv("Entregable(c).csv")

In [12]:
columnas_50 = df.columns[:50]

# Crear el array 2D solo con esas columnas
array_2d = df[columnas_50]

# Mostrar el resultado
print(array_2d)

                        id                                       listing_url  \
0                     2708                 https://www.airbnb.com/rooms/2708
1                     2732                 https://www.airbnb.com/rooms/2732
2                     2864                 https://www.airbnb.com/rooms/2864
3                     6033                 https://www.airbnb.com/rooms/6033
4                     6931                 https://www.airbnb.com/rooms/6931
...                    ...                                               ...
45416  1443394805958459680  https://www.airbnb.com/rooms/1443394805958459680
45417  1443394831515560629  https://www.airbnb.com/rooms/1443394831515560629
45418  1443394885201303898  https://www.airbnb.com/rooms/1443394885201303898
45419  1443449500529637549  https://www.airbnb.com/rooms/1443449500529637549
45420  1443465434447227262  https://www.airbnb.com/rooms/1443465434447227262

            scrape_id last_scraped           source  \
0      20250617032927   2025-06-17      city scrape
1      20250617032927   2025-06-17      city scrape
2      20250617032927   2025-06-17  previous scrape
3      20250617032927   2025-06-17  previous scrape
4      20250617032927   2025-06-17      city scrape
...               ...          ...              ...
45416  20250617032927   2025-06-17      city scrape
45417  20250617032927   2025-06-17      city scrape
45418  20250617032927   2025-06-17      city scrape
45419  20250617032927   2025-06-17      city scrape
45420  20250617032927   2025-06-17      city scrape

                                                    name  \
0      Run Runyon, Beaut Furn Mirror Mini-Suit w/ Fir...
1                                  Zen Life at the Beach
2                 * Beautiful Master Suite/Jacuzzi Tub/*
3                               Poolside Serenity Studio
4      RUN Runyon, Beau Furn Rms Terrace Hollyw Hill ...
...                                                  ...
45416            Motel 6 Claremont, Ca_1 King Bed | Nsmk
45417           Motel 6 Claremont, Ca_2 Queen Beds | Smo
45418           Motel 6 Claremont, Ca_2 Queen Beds | Nsm
45419                           Point Dume Summer Rental
45420  SoCal Getaway Minutes from Disneyland, DTLA &C...

                                             description  \
0      Run Runyon Canyon<br /><br />Gym & Sauna <br /...
1                    An oasis of tranquility awaits you.
2      Centrally located.... Furnished with King Size...
3      Our distinctive bachelor's studio for 1-3 gues...
4      Run Runyon Canyon & Views<br /><br />Gym & Sau...
...                                                  ...
45416            Motel 6 Claremont, Ca_1 King Bed | Nsmk
45417           Motel 6 Claremont, Ca_2 Queen Beds | Smo
45418           Motel 6 Claremont, Ca_2 Queen Beds | Nsm
45419  Relax with the whole family at this peaceful p...
45420  Stay at this centrally located getaway on the ...

                                   neighborhood_overview  \
0      Walk and run to Runyon Canyon, it is open!<br ...
1      This is the best part of Santa Monica. Quiet, ...
2      What makes the neighborhood unique is that the...
3                                                    NaN
4      We are in the middle of one of the great citie...
...                                                  ...
45416                                                NaN
45417                                                NaN
45418                                                NaN
45419                                                NaN
45420                                                NaN

                                             picture_url    host_id  ...  \
0      https://a0.muscache.com/pictures/hosting/Hosti...       3008  ...
1      https://a0.muscache.com/pictures/1082993/c5a99...       3041  ...
2      https://a0.muscache.com/pictures/23817858/de20...       3207  ...
3      https://a0.muscache.com/pictures/458111/986c76...      11619  ...
4      https://a0.muscache.com/pictures/miso/Hosting-...       3008  ...
...                                                  ...        ...  ...
45416  https://a0.muscache.com/pictures/prohost-api/H...  674118442  ...
45417  https://a0.muscache.com/pictures/prohost-api/H...  674118442  ...
45418  https://a0.muscache.com/pictures/prohost-api/H...  674118442  ...
45419  https://a0.muscache.com/pictures/miso/Hosting-...  115170752  ...
45420  https://a0.muscache.com/pictures/miso/Hosting-...   30071757  ...

         price minimum_nights maximum_nights minimum_minimum_nights  \
0      $110.00             30            550                     30
1      $118.00              7             27                      7
2          NaN             30            730                     30
3          NaN             30             30                     30
4      $114.00             30            500                     30
...        ...            ...            ...                    ...
45416  $100.00              1           1125                      1
45417  $100.00              1           1125                      1
45418  $100.00              1           1125                      1
45419  $479.00              3            365                      3
45420  $169.00              1            365                      1

      maximum_minimum_nights minimum_maximum_nights maximum_maximum_nights  \
0                         30                   1125                   1125
1                          7                     27                     27
2                         30                   1125                   1125
3                         30                     30                     30
4                         30                   1125                   1125
...                      ...                    ...                    ...
45416                      1                      1                   1125
45417                      1                      1                   1125
45418                      1                      1                   1125
45419                      3                    365                    365
45420                      1                    365                    365

      minimum_nights_avg_ntm maximum_nights_avg_ntm calendar_updated
0                       30.0                 1125.0              NaN
1                        7.0                   27.0              NaN
2                       30.0                 1125.0              NaN
3                       30.0                   30.0              NaN
4                       30.0                 1125.0              NaN
...                      ...                    ...              ...
45416                    1.0                  223.9              NaN
45417                    1.0                  221.2              NaN
45418                    1.0                  243.6              NaN
45419                    3.0                  365.0              NaN
45420                    1.0                  365.0              NaN

[45421 rows x 50 columns]

*** Generar un Archivo.csv por cada dataframe obtenido en el punto 3. respaldarlo en GitHub. ***

In [13]:
#Filas combinadas y Todas las columnas
df= df.iloc[ :,list(range(2, 8)) + list(range(9, 19)) + list(range(21, 24)) + [26] + [28] + list(range(30, 34)) + [35] + [38] + list(range(40, 43)) + list(range(50, 57)) + list(range(61, 66)) + list(range(67, 73)) + [74] + [78] ]
df.info()

print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45421 entries, 0 to 45420
Data columns (total 50 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   scrape_id                       45421 non-null  int64
 1   last_scraped                    45421 non-null  object
 2   source                          45421 non-null  object
 3   name                            45420 non-null  object
 4   description                     44399 non-null  object
 5   neighborhood_overview           20350 non-null  object
 6   host_id                         45421 non-null  int64
 7   host_url                        45421 non-null  object
 8   host_name                       45416 non-null  object
 9   host_since                      45414 non-null  object
 10  host_location                   34640 non-null  object
 11  host_about                      24875 non-null  object
 12  host_response_time              35028 non-null  object
 13  host_response_rate              35028 non-null  object
 14  host_acceptance_rate            35640 non-null  object
 15  host_is_superhost               43852 non-null  object
 16  host_neighbourhood              35914 non-null  object
 17  host_listings_count             45414 non-null  float64
 18  host_total_listings_count       45414 non-null  float64
 19  host_identity_verified          45414 non-null  object
 20  neighbourhood_cleansed          45421 non-null  object
 21  latitude                        45421 non-null  float64
 22  longitude                       45421 non-null  float64
 23  property_type                   45421 non-null  object
 24  room_type                       45421 non-null  object
 25  bathrooms                       36588 non-null  float64
 26  beds                            36545 non-null  float64
 27  price                           36405 non-null  object
 28  minimum_nights                  45421 non-null  int64
 29  maximum_nights                  45421 non-null  int64
 30  has_availability                41916 non-null  object
 31  availability_30                 45421 non-null  int64
 32  availability_60                 45421 non-null  int64
 33  availability_90                 45421 non-null  int64
 34  availability_365                45421 non-null  int64
 35  calendar_last_scraped           45421 non-null  object
 36  number_of_reviews               45421 non-null  int64
 37  estimated_occupancy_l365d       45421 non-null  int64
 38  estimated_revenue_l365d         36405 non-null  float64
 39  first_review                    32849 non-null  object
 40  last_review                     32849 non-null  object
 41  review_scores_rating            32849 non-null  float64
 42  review_scores_cleanliness       32841 non-null  float64
 43  review_scores_checkin           32833 non-null  float64
 44  review_scores_communication     32839 non-null  float64
 45  review_scores_location          32832 non-null  float64
 46  review_scores_value             32831 non-null  float64
 47  license                         12882 non-null  object
 48  calculated_host_listings_count  45421 non-null  int64
 49  reviews_per_month               32849 non-null  float64
dtypes: float64(14), int64(11), object(25)
memory usage: 17.3+ MB
            scrape_id last_scraped           source  \
0      20250617032927   2025-06-17      city scrape
1      20250617032927   2025-06-17      city scrape
2      20250617032927   2025-06-17  previous scrape
3      20250617032927   2025-06-17  previous scrape
4      20250617032927   2025-06-17      city scrape
...               ...          ...              ...
45416  20250617032927   2025-06-17      city scrape
45417  20250617032927   2025-06-17      city scrape
45418  20250617032927   2025-06-17      city scrape
45419  20250617032927   2025-06-17      city scrape
45420  20250617032927   2025-06-17      city scrape

                                                    name  \
0      Run Runyon, Beaut Furn Mirror Mini-Suit w/ Fir...
1                                  Zen Life at the Beach
2                 * Beautiful Master Suite/Jacuzzi Tub/*
3                               Poolside Serenity Studio
4      RUN Runyon, Beau Furn Rms Terrace Hollyw Hill ...
...                                                  ...
45416            Motel 6 Claremont, Ca_1 King Bed | Nsmk
45417           Motel 6 Claremont, Ca_2 Queen Beds | Smo
45418           Motel 6 Claremont, Ca_2 Queen Beds | Nsm
45419                           Point Dume Summer Rental
45420  SoCal Getaway Minutes from Disneyland, DTLA &C...

                                             description  \
0      Run Runyon Canyon<br /><br />Gym & Sauna <br /...
1                    An oasis of tranquility awaits you.
2      Centrally located.... Furnished with King Size...
3      Our distinctive bachelor's studio for 1-3 gues...
4      Run Runyon Canyon & Views<br /><br />Gym & Sau...
...                                                  ...
45416            Motel 6 Claremont, Ca_1 King Bed | Nsmk
45417           Motel 6 Claremont, Ca_2 Queen Beds | Smo
45418           Motel 6 Claremont, Ca_2 Queen Beds | Nsm
45419  Relax with the whole family at this peaceful p...
45420  Stay at this centrally located getaway on the ...

                                   neighborhood_overview    host_id  \
0      Walk and run to Runyon Canyon, it is open!<br ...       3008
1      This is the best part of Santa Monica. Quiet, ...       3041
2      What makes the neighborhood unique is that the...       3207
3                                                    NaN      11619
4      We are in the middle of one of the great citie...       3008
...                                                  ...        ...
45416                                                NaN  674118442
45417                                                NaN  674118442
45418                                                NaN  674118442
45419                                                NaN  115170752
45420                                                NaN   30071757

                                          host_url     host_name  host_since  \
0           https://www.airbnb.com/users/show/3008         Chas.  2008-09-16
1           https://www.airbnb.com/users/show/3041  Louise-Diane  2008-09-17
2           https://www.airbnb.com/users/show/3207     Bernadine  2008-09-25
3          https://www.airbnb.com/users/show/11619         Sarah  2009-03-28
4           https://www.airbnb.com/users/show/3008         Chas.  2008-09-16
...                                            ...           ...         ...
45416  https://www.airbnb.com/users/show/674118442           Jan  2025-01-20
45417  https://www.airbnb.com/users/show/674118442           Jan  2025-01-20
45418  https://www.airbnb.com/users/show/674118442           Jan  2025-01-20
45419  https://www.airbnb.com/users/show/115170752        Rachel  2017-02-06
45420   https://www.airbnb.com/users/show/30071757       Theresa  2015-03-26

       ... last_review review_scores_rating review_scores_cleanliness  \
0      ...  2024-12-01                 4.86                      4.93
1      ...  2022-08-21                 4.41                      4.58
2      ...         NaN                  NaN                       NaN
3      ...  2020-03-22                 4.38                      4.00
4      ...  2025-06-01                 4.86                      4.91
...    ...         ...                  ...                       ...
45416  ...         NaN                  NaN                       NaN
45417  ...         NaN                  NaN                       NaN
45418  ...         NaN                  NaN                       NaN
45419  ...         NaN                  NaN                       NaN
45420  ...         NaN                  NaN                       NaN

      review_scores_checkin review_scores_communication  \
0                      5.00                        4.98
1                      4.39                        4.48
2                       NaN                         NaN
3                      4.59                        4.35
4                      4.91                        4.91
...                     ...                         ...
45416                   NaN                         NaN
45417                   NaN                         NaN
45418                   NaN                         NaN
45419                   NaN                         NaN
45420                   NaN                         NaN

      review_scores_location review_scores_value     license  \
0                       4.95                4.86         NaN
1                       4.91                4.22      228269
2                        NaN                 NaN         NaN
3                       4.65                4.29         NaN
4                       4.71                4.76         NaN
...                      ...                 ...         ...
45416                    NaN                 NaN         NaN
45417                    NaN                 NaN         NaN
45418                    NaN                 NaN         NaN
45419                    NaN                 NaN  STR22-0034
45420                    NaN                 NaN         NaN

       calculated_host_listings_count reviews_per_month
0                                   2              0.33
1                                   2              0.14
2                                   1               NaN
3                                   6              0.10
4                                   2              0.19
...                               ...               ...
45416                              79               NaN
45417                              79               NaN
45418                              79               NaN
45419                               2               NaN
45420                               2               NaN

[45421 rows x 50 columns]

In [14]:
#Convertir array a CSV
df.to_csv("Entregable(d).csv")

In [ ]:
#Convertir array a CSV
df.to_csv("Entregable1.csv")